### ISSUE TITLE
lru_cache syntax not supported in python <= 3.7

### ISSUE THREAD

**Issue by robertsjames** [JelleAalbers/wimprates#12]
Due to an error coming from` functools`:

```
in lru_cache(maxsize, typed)
    488             maxsize = 0
    489     elif maxsize is not None:
--> 490         raise TypeError('Expected maxsize to be an integer or None')
    491 
    492     def decorating_function(user_function):
```

Seems to be related to the `@lru_cache` decorator added to `read_migdal_transitions `

**Comment by JelleAalbers** [comment]
Thanks for the heads up! Indeed, the `lru_cache(function)` syntax is only supported on python 3.8, before that you have to write `lru_cache(maxsize=something)(function)`.

While python 3.6 is beyond end of life (https://endoflife.date/python), we should certainly still support python 3.7. And the fix is small anyway.

**Comment by robertsjames** [comment]
I think google colab still uses 3.6

**Comment by JelleAalbers** [comment]
I got python 3.7 with them yesterday, but this lru_cache syntax only works starting in python 3.8
